[build]
  base = "expense"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "20" # Match your local Node.js version
  NEXT_NETLIFY_PLUGIN_SKIP_INSTALL = "true" # Skip reinstalling the plugin

# Use the Next.js Runtime
[[plugins]]
  package = "@netlify/plugin-nextjs"

# For fallback routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = false

# Handle Next.js static files with proper caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"
